name: Update Age in README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Calculate age and update README
        run: |
          npm install -g age-calculator
          AGE=$(node -e "console.log(require('age-calculator').AgeFromDateString('2005-10-03').getYears())")
          sed -i "s/Никита, \*script\* лет/Никита, $AGE лет/g" README.md
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update age in README"
          git push
